### ISSUE TITLE
Unreal 5无效，改变shadermodel会有影响

### ISSUE THREAD

**Issue by hanbim520** [Eragon-Brisingr/ToonShader#1]
如题问题，我放在https://github.com/hanbim520/UE4ShaderPluginDemo.git了，unreal 5  preview 2，shadermodel变量没有效果，不过matrial 下面的shadermodel改变还是会有效果，这就意味着改动的代码有些会被计算两边吧

**Comment by hanbim520** [comment]
close #1

**Comment by Eragon-Brisingr** [comment]
Unfortunately, UE5 EA has some change let can not enable other data buffer without change soruce code. So the way only enable in under 4.26 engine.

**Comment by kriNon** [comment]
Have you looked at UE5.1?
I think it might be possible to add shader models using the new strata materials system.

**Comment by Eragon-Brisingr** [comment]
> Have you looked at UE5.1? I think it might be possible to add shader models using the new strata materials system.

Not yet, can you hint me some idea?

**Comment by kriNon** [comment]
I think we can implement shading models in StrataEvaluation.ush
Maybe the strata module can be overridden?

Maybe we can insert code somehow? Shader File Preprocessing?

**Comment by Eragon-Brisingr** [comment]
https://github.com/Eragon-Brisingr/ToonShader/blob/453bba959c19119d393bc22658ee8b8369303282/Source/ToonShaderBootstrap/Private/ToonShaderBootstrap.cpp#L17-L37

BootstrapModule replace engine shader file. (Shader File Preprocessing

But we can not enable other data buffer without change soruce code, because UE5 flexible GBuffer is enable.
[First major checkin for flexible GBuffer.
](https://github.com/EpicGames/UnrealEngine/commit/5f3ff39aed341bce1a7c7c1a6d0c75f5870329dc)

**Comment by kriNon** [comment]
Why is flexible GBuffer an issue?

How do the other strata materials work with flexible GBuffer?

**Comment by Eragon-Brisingr** [comment]
When no flexible GBuffer, standard shader model has additional two GBuffer can use, but when flexible GBuffer enable, every shader model know max use GBuffer count, so additional GBuffer is gone.

**Comment by kriNon** [comment]
![image](https://user-images.githubusercontent.com/3295424/170675994-129c74d3-0d75-46b9-a961-ac7b08b11726.png)
Can we do it the same way this works? Or we can't use GBuffer.customData?

**Comment by Eragon-Brisingr** [comment]
I think only change engine source code to enable additional data buffer...
